routes/web.php
<?php

use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\LogoutController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/data-complaint', ComplaintController::class);

// Route::resource('/data-responses.index', ComplaintController::class);



Route::post('/logout', [LogoutController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'showLoginForm'])->name('Student-login');
Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'login'])->name('Student-login');
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');



Route::get('/create-siswa', [App\Http\Controllers\DatasiswaController::class, 'create'])->name('create-siswa');
Route::post('/simpan-siswa', [App\Http\Controllers\DatasiswaController::class, 'store'])->name('simpan-siswa');
Route::get('/edit-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'edit'])->name('edit-siswa');
Route::post('/update-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'update'])->name('update-siswa');
Route::delete('delete-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'destroy'])->name('delete-siswa');


Route::delete('/delete-laporan/{id}', [App\Http\Controllers\LaporanController::class, 'destroy'])->name('delete-laporan');
Route::post('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/data-siswa', [App\Http\Controllers\DatasiswaController::class, 'index'])->name('data-siswa');
Route::get('/laporan-bully', [App\Http\Controllers\HomehalamanController::class, 'index'])->name('halaman-home');
Route::get('/simpan-laporan', [App\Http\Controllers\HomehalamanController::class, 'store'])->name('halaman-home');
Route::get('/halaman-home', [App\Http\Controllers\HomehalamanController::class, 'create'])->name('halaman-home');
Route::get('/logout', [App\Http\Controllers\LoginController::class, 'logout']);

Route::get('/create-pengaduan', [App\Http\Controllers\LaporanController::class, 'create'])->name('create-pengaduan');
Route::get('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');
Route::post('/simpan-laporan', [App\Http\Controllers\LaporanController::class, 'store'])->name('simpan-laporan');

Route::get('/tanggapan-petugas', [App\Http\Controllers\ResponsController::class, 'index'])->name('tanggapan-petugas');
Route::get('/cetak-laporan', [App\Http\Controllers\LaporanController::class, 'cetaklaporan'])->name('cetak-laporan');

// controller buat edit//
Route::put('/perundungan/{id}/update', [App\Http\Controllers\PerundunganController::class, 'update'])->name('perundungan.update');

Route::get('/about', function () {
    return view('about');
});

resources/views/pages/admin/dashboard.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')
@section('content')

    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1></h1>
            </div>
            <div class="section-body">
            </div>
            <div class="card-body">
                <h5>Ingatlah bahwa pekerjaanmu bukan hanya sekadar sebuah pekerjaan, tapi juga merupakan tanggung jawab
                    sosialmu. Oleh karena itu, lakukanlah pekerjaanmu dengan baik dan jujur, demi kebaikan bersama.
                </h5>
            </div>
            <div class="card-header float-right">
                <a href="{{ route('data-complaint.create') }}" class="btn btn-danger">LAPOR!</a>
                <div class="card-header-action">
                </div>
            </div>
    </div>
    </div>
    </section>
    </div>

    </section>
    </div>

@endsection

resources/views/pages/admin/login.blade.php
@extends('layouts.admin')
@section('title', 'Login')

@section('content')
  
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="login-brand">
              <img src="assets/img/stisla-fill.svg" alt="logo" width="100" class="shadow-light rounded-circle">
            </div>

            <div class="card card-primary">
              <div class="card-header"><h4>Login</h4></div>

              <div class="card-body">
                <form method="POST" action="#" class="needs-validation" novalidate="">
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-control" name="email" tabindex="1" required autofocus>
                    <div class="invalid-feedback">
                      Please fill in your email
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="d-block">
                    	<label for="password" class="control-label">Password</label>
                      <div class="float-right">
                        <a href="auth-forgot-password.html" class="text-small">
                          Forgot Password?
                        </a>
                      </div>
                    </div>
                    <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
                    <div class="invalid-feedback">
                      please fill in your password
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
                      <label class="custom-control-label" for="remember-me">Remember Me</label>
                    </div>
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </div>
                </form>
              </div>
            </div>
            <div class="mt-5 text-muted text-center">
              Don't have an account? <a href="auth-register.html">Create One</a>
            </div>
            <div class="simple-footer">
              Copyright &copy; Stisla 2018
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

            @endsection

resources/views/pages/admin/tanggapan-petugas.blade.php
@extends('layouts.admin')
@section('title', 'Report')
@section('content')

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>

    <!-- Main content -->

    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Tanggapan</h1>
            </div>
            <div class="section-body">
                <div class="row">
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">

                            <div class="card-body p-0">
                                <div class="table-responsive p-3">
                                    <table class="table table-striped" id="complaintTable">
                                        <thead>
                                            <tr>
                                                <th>id</th>
                                                <th>school_class</th>
                                                <th>report_title</th>
                                                <th>report_detail</th>
                                                <th>incident_time</th>
                                                <th>place</th>
                                                <th>type_of_bullying</th>
                                                <th>victim_name</th>
                                                <th>class</th>
                                                <th>reporter_id</th>
                                                <th>proof</th>
                                                <th>responses</th>
                                                <th>verification</th>
                                            </tr>
                                            @foreach ($complaint as $i => $sis)
                                                <tr>
                                                    <td>{{ $sis->id }}</td>
                                                    <td>{{ $sis->school_class }}</td>
                                                    <td>{{ $sis->report_title }}</td>
                                                    <td>{{ $sis->report_detail }}</td>
                                                    <td>{{ date('d-m-y', strtotime($sis->incident_time)) }}</td>
                                                    <td>{{ $sis->place }}</td>
                                                    <td>{{ $sis->type_of_bullying }}</td>
                                                    <td>{{ $sis->victim_name }}</td>
                                                    <td>{{ $sis->class }}</td>
                                                    <td>{{ $sis->reporter_id }}</td>
                                                    <td>{{ $sis->proof }}</td>

                                                    <td>
                                                        <form method="POST"
                                                            action="{{ route('perundungan.update', ['id' => $sis->id]) }}">
                                                            @csrf
                                                            @method('PUT')
                                                            <div class="form-group">
                                                                <select class="form-control selectric" name="responses">
                                                                    <option value="Confirmed"
                                                                        {{ $sis->responses == 'Confirmed' ? 'selected' : '' }}>
                                                                        Confirmed</option>
                                                                    <option value="Hoax"
                                                                        {{ $sis->responses == 'Hoax' ? 'selected' : '' }}>
                                                                        Hoax</option>
                                                                </select>
                                                            </div>
                                                            <button type="submit" class="btn btn-primary">Update
                                                                Responses</button>
                                                        </form>
                                                    </td>

                                                    <td>
                                                        <form method="POST"
                                                            action="{{ route('perundungan.update', ['id' => $sis->id]) }}">
                                                            @csrf
                                                            @method('PUT')
                                                            <div class="form-group">
                                                                <select class="form-control selectric" name="verification">
                                                                    <option value="waiting"
                                                                        {{ $sis->verification == 'waiting' ? 'selected' : '' }}>
                                                                        Waiting</option>
                                                                    <option value="process"
                                                                        {{ $sis->verification == 'process' ? 'selected' : '' }}>
                                                                        Process</option>
                                                                    <option value="finished"
                                                                        {{ $sis->verification == 'finished' ? 'selected' : '' }}>
                                                                        Finished</option>
                                                                </select>
                                                            </div>
                                                            <button type="submit" class="btn btn-primary">Update
                                                                Verification</button>
                                                        </form>
                                                    </td>

                                                    <td>
                                                        <form action="{{ url('delete-laporan', $sis->id) }}"
                                                            class="d-inline" method="POST"
                                                            id="delete-form-{{ $sis->id }}">
                                                            @csrf
                                                            @method('delete')
                                                            <button type="button" class="btn btn-danger"
                                                                onclick="deleteData('{{ $sis->id }}')">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endsection

        @push('addon-script')
            <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.13.3/js/dataTables.bootstrap5.min.js"></script>

            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
            <script>
                $(document).ready(function() {
                    $('#complaintTable').DataTable()
                })


                function deleteData(id) {
                    Swal.fire({
                        title: 'PERINGATAN!',
                        text: 'YAKIN INGIN MENGHAPUS?',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yakin',
                        cancelButtonText: 'Batal',
                    }).then((result) => {
                        if (result.value) {
                            $('#delete-form-' + id).submit();
                        }
                    });
                }
            </script>
        @endpush