routes/web.php
<?php

use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\LogoutController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/data-complaint', ComplaintController::class);

// Route::resource('/data-responses.index', ComplaintController::class);



Route::post('/logout', [LogoutController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'showLoginForm'])->name('Student-login');
Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'login'])->name('Student-login');
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');



Route::get('/create-siswa', [App\Http\Controllers\DatasiswaController::class, 'create'])->name('create-siswa');
Route::post('/simpan-siswa', [App\Http\Controllers\DatasiswaController::class, 'store'])->name('simpan-siswa');
Route::get('/edit-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'edit'])->name('edit-siswa');
Route::post('/update-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'update'])->name('update-siswa');
Route::delete('delete-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'destroy'])->name('delete-siswa');


Route::delete('/delete-laporan/{id}', [App\Http\Controllers\LaporanController::class, 'destroy'])->name('delete-laporan');
Route::post('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/data-siswa', [App\Http\Controllers\DatasiswaController::class, 'index'])->name('data-siswa');
Route::get('/laporan-bully', [App\Http\Controllers\HomehalamanController::class, 'index'])->name('halaman-home');
Route::get('/simpan-laporan', [App\Http\Controllers\HomehalamanController::class, 'store'])->name('halaman-home');
Route::get('/halaman-home', [App\Http\Controllers\HomehalamanController::class, 'create'])->name('halaman-home');
Route::get('/logout', [App\Http\Controllers\LoginController::class, 'logout']);

Route::get('/create-pengaduan', [App\Http\Controllers\LaporanController::class, 'create'])->name('create-pengaduan');
Route::get('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');
Route::post('/simpan-laporan', [App\Http\Controllers\LaporanController::class, 'store'])->name('simpan-laporan');

Route::get('/tanggapan-petugas', [App\Http\Controllers\ResponsController::class, 'index'])->name('tanggapan-petugas');
Route::get('/cetak-laporan', [App\Http\Controllers\LaporanController::class, 'cetaklaporan'])->name('cetak-laporan');

// controller buat edit//
Route::put('/perundungan/{id}/update', [App\Http\Controllers\PerundunganController::class, 'update'])->name('perundungan.update');

Route::get('/about', function () {
    return view('about');
});

resources/views/pages/admin/responses/index.blade.php
@extends('layouts.admin')
@section('title', 'complaint')

@section('content')

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>


      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>complaint</h1>
          </div>
          <div class="section-body">
            <div class="row">
            </div>
            <div class="row">
              <div class="col-12">
                <div class="card">

                  <div class="card-body p-0">
                    <div class="table-responsive p-3">
                      <table class="table table-striped" id="complaintTable">
                        <thead>
                          <tr>
                            <th>ID</th>
                            <th>VICTIMS NAME</th>
                            <th>GRADE</th>
                            <th>TITLE</th>
                            <th>TYPE OF BULYING</th>
                            <th>TIME HAPPEND</th>
                            <th>STATUS</th>
                            <th>ACTION</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($complaint as $i => $com)
                            <tr>
                              <td>{{ $i += 1 }}</td>
                              <td>{{ $com -> victim_name }}</td>
                              <td>{{ $com -> grade }}</td>
                              <td>{{ $com -> report_title }}</td>
                              <td>{{ $com -> type_of_bullying }}</td>
                              <td>{{ $com -> incident_time }}</td>
                              <td>
                                <a href="{{ route('data-complaint.edit', $com->id) }}" class="btn btn-primary">Edit </a>
                              </td>
                              <td>
                                <form action="{{ url('data-complaint', $com->id) }}" class="d-inline" method="POST" id="delete{{$com->id}}">
                                  @csrf
                                  @method('delete')
                                  <button type="button" class="btn btn-danger" onclick="deleteData('{{$com->id}}')">Delete</button>
                                </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-header float-right">
            <a href="/data-complaint/create" class="btn btn-danger">Tambah</a>
            <div class="card-header-action">
            </div>
          </div>
        </section>
      </div>
@endsection

@push('addon-script')
<script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.3/js/dataTables.bootstrap5.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
  $(document).ready(function(){
      $('#complaintTable').DataTable()
  })


  function deleteData(id){
    Swal.fire({
      title: 'PERINGATAN!',
      text: 'YAKIN INGIN MENGHAPUS?',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yakin',
      cancelButtonText: 'Batal',

    }).then((result) => {
      if(result.value) {
        $('#delete' +id).submit();
      }
    });

  }
</script>
@endpush