routes/web.php
<?php

use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\LogoutController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/data-complaint', ComplaintController::class);

// Route::resource('/data-responses.index', ComplaintController::class);



Route::post('/logout', [LogoutController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'showLoginForm'])->name('Student-login');
Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'login'])->name('Student-login');
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');



Route::get('/create-siswa', [App\Http\Controllers\DatasiswaController::class, 'create'])->name('create-siswa');
Route::post('/simpan-siswa', [App\Http\Controllers\DatasiswaController::class, 'store'])->name('simpan-siswa');
Route::get('/edit-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'edit'])->name('edit-siswa');
Route::post('/update-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'update'])->name('update-siswa');
Route::delete('delete-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'destroy'])->name('delete-siswa');


Route::delete('/delete-laporan/{id}', [App\Http\Controllers\LaporanController::class, 'destroy'])->name('delete-laporan');
Route::post('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/data-siswa', [App\Http\Controllers\DatasiswaController::class, 'index'])->name('data-siswa');
Route::get('/laporan-bully', [App\Http\Controllers\HomehalamanController::class, 'index'])->name('halaman-home');
Route::get('/simpan-laporan', [App\Http\Controllers\HomehalamanController::class, 'store'])->name('halaman-home');
Route::get('/halaman-home', [App\Http\Controllers\HomehalamanController::class, 'create'])->name('halaman-home');
Route::get('/logout', [App\Http\Controllers\LoginController::class, 'logout']);

Route::get('/create-pengaduan', [App\Http\Controllers\LaporanController::class, 'create'])->name('create-pengaduan');
Route::get('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');
Route::post('/simpan-laporan', [App\Http\Controllers\LaporanController::class, 'store'])->name('simpan-laporan');

Route::get('/tanggapan-petugas', [App\Http\Controllers\ResponsController::class, 'index'])->name('tanggapan-petugas');
Route::get('/cetak-laporan', [App\Http\Controllers\LaporanController::class, 'cetaklaporan'])->name('cetak-laporan');

// controller buat edit//
Route::put('/perundungan/{id}/update', [App\Http\Controllers\PerundunganController::class, 'update'])->name('perundungan.update');

Route::get('/about', function () {
    return view('about');
});

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Complaint;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $complaint = Complaint::all();
        return view('pages.student.pengaduan', ['complaint' =>$complaint ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/pages/student/cetak-laporan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        table.stati {}

    </style>
    <title>CETAK PENGADUAN</title>
</head>
<body>
    <div class="form-group">
        <p align="center"><b>Laporan Data Pegawai</b></p>
        <table class="static" align="center" rules="all" border="1px" style="width: 95%;"></table>
        <tr>
            <th>id</th>
            <th>school_class</th>
            <th>report_title</th>
            <th>report_detail</th>
            <th>incident_time</th>
            <th>place</th>
            <th>type_of_bullying</th>
            <th>victim_name</th>
            <th>class</th>
            <th>reporter_name</th>
            <th>proof</th>
            <th>photo_desription</th>
            <th>responses</th>
            <th>verification</th>
        </tr>
        <tr>
            @foreach ($cetakcomplaint as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->school_class }}</td>
                <td>{{ $item->report_title }}</td>
                <td>{{ $item->report_detail }}</td>
                <td>{{ date('d-m-y', strtotime($item->incident_time)) }}</td>
                <td>{{ $item->place }}</td>
                <td>{{ $item->type_of_bullying }}</td>
                <td>{{ $item->victim_name }}</td>
                <td>{{ $item->class }}</td>
                <td>{{ $item->reporter_name }}</td>
                <td>{{ $item->proof }}</td>
                <td>{{ $item->photo_desription }}</td>
                <td>{{ $item->responses }}</td>
                <td>{{ $item->verification }}</td>
                <td>
            @endforeach
        </tr>
    </div>
</body>
</html>

resources/views/pages/student/create-pengaduan.blade.php
@stack('prepend-style')
@include('include.style')
@stack('addon-style')

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-94034622-3');
</script>

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="{{ url('home') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Kembali</h1>
        </div>

        <div class="section-body">
            <h2 class="section-title">Sampaikan Laporan Mu</h2>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Write Your Post</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('data-complaint.store') }}"
                                enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul
                                        Laporan</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" value="{{ old('id') }}" required
                                            name="report_title">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Detail
                                        Laporan</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="detail" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Waktu
                                        Kejadian</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="datetime-local" class="form-control" value="{{ old('id') }}"
                                            required name="incident_time">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tempat
                                        Kejadian</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" value="{{ old('id') }}" required
                                            name="place">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis
                                        Perundungan</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control selectric" name="type_of_bullying">
                                            @foreach ($type_of_bullying as $item)
                                                <option value="{{ $item }}">{{ $item }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="card-header">
                                    <h4>Data Korban</h4>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama
                                        Korban</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" value="{{ old('id') }}" required
                                            name="victim_name">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tingkat
                                        Pendidikan</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control selectric" name="school_class">
                                            @foreach ($class as $item)
                                                <option value="{{ $item }}">{{ $item }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis
                                        Kelamin</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control selectric" value="{{ old('id') }}" required
                                            name="jenis_kelamin">
                                            @foreach ($gender as $item)
                                                <option value="{{ $item }}">{{ $item }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="card-header">
                                    <h4>Data Pelapor</h4>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Id
                                        Pelapor</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select name="reporter_id" class="form-control selectric">
                                            @foreach ($users as $user)
                                                <option value="{{ $user->id }}">{{ $user->id }} -
                                                    {{ $user->username }}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tingkat
                                        Pendidikan</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control selectric" name="class">
                                            @foreach ($class as $item)
                                                <option value="{{ $item }}">{{ $item }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Bukti</label>
                                    <div class="col-sm-12 col-md-7">
                                        <div id="image-preview" class="image-preview">
                                            <label for="image-upload" id="image-label">Choose File</label>
                                            <input type="file" name="proof" id="image-upload" optional
                                                name="proof">
                                        </div>
                                    </div>
                                </div>

                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('kirim') }}
                                    </button>
                                </div>
                        </div>
                        </form>
                        @if ($errors->any())
                            @foreach ($errors->all() as $error)
                                <p class="text-danger">{{ $error }}</p>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
    </section>
</div>
</div>
</div>

@include('sweetalert::alert')
@stack('prepend-script')
@include('include.script')
@stack('addon-script')

resources/views/pages/student/halaman-home.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Halaman Home Pengaduan</title>
    <link rel="stylesheet" href="{{ asset('css/style.css ')}}">
</head>

<body>
    <header>
        <h1>Laporkan Pengaduanmu!</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Tentang Ara!</a></li>
                <li><a href="#">Lapor!</a></li>
                <li>
                </li>
                @if (Route::has('login'))
                <div class="sm:fixed sm:top-0 sm:right-0 p-6 text-right">
                    @auth
                        <a href="{{ url('/home') }}" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Home</a>
                    @else
                        <a href="{{ route('login') }}" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Log in</a>
                        
                        @if (Route::has('register'))
                            <a href="{{ route('register') }}" class="ml-4 font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Register</a>
                        @endif
                    @endauth
                </div>
            @endif
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h2>Laporan Pengaduan Bully Anda</h2>
            <form action="{{ route('laporan-bully')}}" method="post" enctype="multipart/form-data">
              {{ csrf_field()}}
              <div class="form-group">
                <input type="text" id="school_class" name="school_class" class="form-control" placeholder="school_class"> 
                </div>
              <div class="form-group">
                <input type="text" id="report_title" name="report_title" class="form-control" placeholder="report_title"> 
                </div>
                <div class="form-group">
                  <textarea name="report_detail" id="report_detail"  class="form-control" placeholder="report_detail"></textarea>
                  </div>
                <div class="form-group">
                  <input type="date" id="incident_time" name="incident_time" class="form-control" placeholder="incident_time"> 
                  </div>
                <div class="form-group">
                  <input type="text" id="place" name="place" class="form-control" placeholder="place"> 
                  </div>
                <div class="form-group">
                  <input type="text" id="type_of_bullying" name="type_of_bullying" class="form-control" placeholder="type_of_bullying"> 
                  </div>
                <div class="form-group">
                  <input type="text" id="victim_name" name="victim_name" class="form-control" placeholder="victim_name"> 
                  </div>
                <div class="form-group">
                    <input type="text" id="class" name="class" class="form-control" placeholder="class"> 
                  </div>
                <div class="form-group">
                  <input type="text" id="reporter_name" name="reporter_name" class="form-control" placeholder="reporter_name"> 
                  </div>
                <div class="form-group">
                    <label for="">Proof</label>
                  <input type="file" id="proof" name="proof"> 
                  </div>
                <div class="form-group">
                  <textarea name="photo_desription" id="photo_desription"  class="form-control" placeholder="photo_desription"></textarea>
                  </div>
                
                  
                  <div class="form-group">
                    <button type="submit" class="btn btn-success">Simpan</button>
                  </div>
              </form>
        </section>
    </main>
    <section class="section-footer">
      <footer>
        <div class="container">
        <div class="row row-sub-footer">
          <div class="col-12 col-md-6 col-lg-3 ps-1">
            <div class="wrapper-col-1 mb-5">
              <h1>Ara Application</h1>
              <p class="mb-4">Lorem ipsum dolor sit amet, <br> consectetur adipiscing elit, sed do <br> elusmod tempor incididunt ut labore<br> et dolore magna aliqua. Ut enim ad</p>
              <div class="wrapper-icon d-flex">
                <a href="#"><img src="/public/image/facebook.png" alt=""></a>
                <a href="#"><img src="/public/image/twitter.png" alt=""></a>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3 ps-5">
            <div class="wrapper-col-2 mb-5">
              <h1>Useful links</h1>
              <a href="#">Blog</a>
              <a href="#">Hewan</a>
              <a href="#">Galeri</a>
              <a href="#">Testimonial</a>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <div class="wrapper-col-3 mb-5">
              <h1>Privacy</h1>
              <a href="#">Karir</a>
              <a href="#">Tentang Kami</a>
              <a href="#">Kontak kami</a>
              <a href="#">Servis</a>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3 mb-5">
            <div class="wrapper-col-4">
              <h1>Contact Info</h1>
              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="18.829" height="14.834" viewBox="0 0 18.829 14.834">
              <defs>
                <style>
                  .cls-1 {
                    fill: none;
                    stroke: #fff;
                    stroke-linecap: round;
                    stroke-linejoin: round;
                    stroke-width: 2px;
                  }
                </style>
              </defs>
              <g id="mail" transform="translate(-0.607 -3)">
                <path id="Path_25" data-name="Path 25" class="cls-1" d="M3.6,4H16.439a1.609,1.609,0,0,1,1.6,1.6V15.23a1.609,1.609,0,0,1-1.6,1.6H3.6A1.609,1.609,0,0,1,2,15.23V5.6A1.609,1.609,0,0,1,3.6,4Z"/>
                <path id="Path_26" data-name="Path 26" class="cls-1" d="M18.043,6l-8.022,5.615L2,6" transform="translate(0 -0.396)"/>
              </g>
            </svg> tropisianimal@gmail.com </a>
              <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="18.044" height="18.077" viewBox="0 0 18.044 18.077">
                <defs>
                  <style>
                    .cls-1 {
                      fill: none;
                      stroke: #fff;
                      stroke-linecap: round;
                      stroke-linejoin: round;
                      stroke-width: 2px;
                    }
                  </style>
                </defs>
                <path id="phone" class="cls-1" d="M18.155,14.035v2.42A1.613,1.613,0,0,1,16.4,18.068a15.963,15.963,0,0,1-6.961-2.476,15.73,15.73,0,0,1-4.84-4.84A15.963,15.963,0,0,1,2.118,3.758,1.613,1.613,0,0,1,3.724,2h2.42A1.613,1.613,0,0,1,7.757,3.387a10.357,10.357,0,0,0,.565,2.267,1.613,1.613,0,0,1-.363,1.7L6.934,8.381a12.906,12.906,0,0,0,4.84,4.84L12.8,12.2a1.613,1.613,0,0,1,1.7-.363,10.357,10.357,0,0,0,2.267.565,1.613,1.613,0,0,1,1.387,1.637Z" transform="translate(-1.111 -1)"/>
              </svg>
               +62 812 3456 7890</a>
              <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="15.128" height="18.045" viewBox="0 0 15.128 18.045">
              <defs>
                <style>
                  .cls-1 {
                    fill: none;
                    stroke: #fff;
                    stroke-linecap: round;
                    stroke-linejoin: round;
                    stroke-width: 2px;
                  }
                </style>
              </defs>
              <g id="map-pin" transform="translate(-2)">
                <path id="Path_27" data-name="Path 27" class="cls-1" d="M16.128,7.564c0,5.105-6.564,9.481-6.564,9.481S3,12.669,3,7.564a6.564,6.564,0,1,1,13.128,0Z"/>
                <circle id="Ellipse_17" data-name="Ellipse 17" class="cls-1" cx="2.5" cy="2.5" r="2.5" transform="translate(7 5.046)"/>
              </g>
            </svg>
             Kota Bandung, Jawa Barat</a>
            </div>
          </div>
        </div>
        <div class="wrapper-last-footer">
          <div class="copyright text-white" style="text-align: center;">Copyright @2020 All righs reserved</div>
        </div>
      </div>
      <div class="py-3">
      </div>
      </footer>
    </section>
</body>
</html>

resources/views/pages/student/laporan-bully.blade.php
@extends('layouts.admin')
@section('title', 'complaint')

@section('content')

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>

    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Laporan Siswa</h1>
            </div>
            <div class="section-body">
                <div class="row">
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">

                            <div class="card-body p-0">
                                <div class="table-responsive p-3">
                                    <table class="table table-striped" id="user">
                                        <thead>
                                            <th>ID</th>
                                            <th>Kelas Sekolah</th>
                                            <th>Judul Laporan</th>
                                            <th>Detail Laporan</th>
                                            <th>Waktu Kejadian</th>
                                            <th>Tempat Kejadian</th>
                                            <th>Jenis Bullying</th>
                                            <th>Nama Korban</th>
                                            <th>Kelas</th>
                                            <th>Nama Pelapor</th>
                                            <th>Bukti</th>

                                            <th>responses</th>
                                            <th class="d-print-none">verification</th>
                                            </tr>
                                            @foreach ($complaint as $i => $sis)
                                                <tr>
                                                    <td>{{ $sis->id }}</td>
                                                    <td>{{ $sis->school_class }}</td>
                                                    <td>{{ $sis->report_title }}</td>
                                                    <td>{{ $sis->report_detail }}</td>
                                                    <td>{{ date('d-m-y', strtotime($sis->incident_time)) }}</td>
                                                    <td>{{ $sis->place }}</td>
                                                    <td>{{ $sis->type_of_bullying }}</td>
                                                    <td>{{ $sis->victim_name }}</td>
                                                    <td>{{ $sis->class }}</td>
                                                    <td>{{ $sis->reporter_name }}</td>
                                                    <td>{{ $sis->proof }}</td>

                                                    <td>
                                                        @if ($sis->responses == 'Pending')
                                                            <a href="{{ route('edit-siswa', $sis->id) }}"
                                                                class="btn btn-secondary">{{ $sis->responses }}</a>
                                                        @elseif($sis->responses == 'Accepted')
                                                            <a href="#"
                                                                class="btn btn-success">{{ $sis->responses }}</a>
                                                        @else
                                                            <a href="#"
                                                                class="btn btn-outline-dark">{{ $sis->responses }}</a>
                                                        @endif
                                                    </td>
                                                    <td>
                                                        @if ($sis->verification == 'Pending')
                                                            <a href="{{ url('', $sis->id) }}"
                                                                class="btn btn-primary">{{ $sis->verification }}</a>
                                                        @elseif($sis->verification == 'Accepted')
                                                            <a href="#"
                                                                class="btn btn-success">{{ $sis->verification }}</a>
                                                        @else
                                                            <a href="#"
                                                                class="btn btn-outline-dark">{{ $sis->verification }}</a>
                                                        @endif
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="content">
                            <div class="card card-info card-outline">
                                <div class="card-header">
                                    <div class="card-tools ml-auto">
                                        <button onclick="window.print()" class="btn btn-default"><i
                                                class="fas fa-print"></i>
                                            Print</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
    </div>
    </div>

    @push('addon-script')
        <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.3/js/dataTables.bootstrap5.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @endpush

@endsection