routes/web.php
<?php

use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\LogoutController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/data-complaint', ComplaintController::class);

// Route::resource('/data-responses.index', ComplaintController::class);



Route::post('/logout', [LogoutController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'showLoginForm'])->name('Student-login');
Route::get('/Student-login', [App\Http\Controllers\Auth\SiswaLoginController::class, 'login'])->name('Student-login');
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');



Route::get('/create-siswa', [App\Http\Controllers\DatasiswaController::class, 'create'])->name('create-siswa');
Route::post('/simpan-siswa', [App\Http\Controllers\DatasiswaController::class, 'store'])->name('simpan-siswa');
Route::get('/edit-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'edit'])->name('edit-siswa');
Route::post('/update-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'update'])->name('update-siswa');
Route::delete('delete-siswa/{id}', [App\Http\Controllers\DatasiswaController::class, 'destroy'])->name('delete-siswa');


Route::delete('/delete-laporan/{id}', [App\Http\Controllers\LaporanController::class, 'destroy'])->name('delete-laporan');
Route::post('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/data-siswa', [App\Http\Controllers\DatasiswaController::class, 'index'])->name('data-siswa');
Route::get('/laporan-bully', [App\Http\Controllers\HomehalamanController::class, 'index'])->name('halaman-home');
Route::get('/simpan-laporan', [App\Http\Controllers\HomehalamanController::class, 'store'])->name('halaman-home');
Route::get('/halaman-home', [App\Http\Controllers\HomehalamanController::class, 'create'])->name('halaman-home');
Route::get('/logout', [App\Http\Controllers\LoginController::class, 'logout']);

Route::get('/create-pengaduan', [App\Http\Controllers\LaporanController::class, 'create'])->name('create-pengaduan');
Route::get('/laporan-bully', [App\Http\Controllers\LaporanController::class, 'index'])->name('laporan-bully');
Route::post('/simpan-laporan', [App\Http\Controllers\LaporanController::class, 'store'])->name('simpan-laporan');

Route::get('/tanggapan-petugas', [App\Http\Controllers\ResponsController::class, 'index'])->name('tanggapan-petugas');
Route::get('/cetak-laporan', [App\Http\Controllers\LaporanController::class, 'cetaklaporan'])->name('cetak-laporan');

// controller buat edit//
Route::put('/perundungan/{id}/update', [App\Http\Controllers\PerundunganController::class, 'update'])->name('perundungan.update');

Route::get('/about', function () {
    return view('about');
});

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Complaint;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $complaint = Complaint::all();
        return view('pages.student.pengaduan', ['complaint' =>$complaint ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/pages/admin/student/edit.blade.php
@extends('layouts.admin')
@section('title', 'edit')
@section('content')


    
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Create New Post</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="#">Posts</a></div>
              <div class="breadcrumb-item">Create New Post</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Create New Post</h2>
            <p class="section-lead">
              On this page you can create a new post and fill in all fields.
            </p>

            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Write Your Post</h4>
                  </div>
                  <div class="card-body">
                  <form action="{{ route('data-complaint.update', $complaint->status) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                    </div>
                  </form>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ $complaint->status }}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Detail Laporan</label>
                      <div class="col-sm-12 col-md-7">
                        <textarea class="summernote-simple" value="{{ old('id')}}" required></textarea>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Waktu Kejadian</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tempat</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis Perundungan</label>
                      <div class="col-sm-12 col-md-7">
                        <select class="form-control selectric">
                          <option>-</option>
                          <option>Physical bullying</option>
                          <option>Verbal bullying</option>
                          <option>Social bullying</option>
                          <option>Psychological bullying</option>
                          <option>Cyberbullying</option>
                          <option>Sexual bullying</option>
                        </select>
                      </div>
                    </div>
                    <div class="card-header">
                      <h4>Data Korban</h4>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Korban</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tingkat Pendidikan</label>
                      <div class="col-sm-12 col-md-7">
                        <select class="form-control selectric">
                          <option>-</option>
                          <option>SD</option>
                          <option>SMP</option>
                          <option>SMK</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kelas</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis Kelamin</label>
                      <div class="col-sm-12 col-md-7">
                        <select class="form-control selectric" value="{{ old('id')}}" required>
                          <option>-</option>
                          <option>Pria</option>
                          <option>Wanita</option>
                        </select>
                      </div>
                    </div>

                    <div class="card-header">
                      <h4>Data Pelapor</h4>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Pelapor</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tingkat Pendidikan</label>
                      <div class="col-sm-12 col-md-7">
                        <select class="form-control selectric">
                          <option>-</option>
                          <option>SD</option>
                          <option>SMP</option>
                          <option>SMK</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kelas</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis Kelamin</label>
                      <div class="col-sm-12 col-md-7">
                        <select class="form-control selectric">
                          <option>-</option>
                          <option>Pria</option>
                          <option>Wanita</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nomor Telepon</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" value="{{ old('id')}}" required>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Bukti</label>
                      <div class="col-sm-12 col-md-7">
                        <div id="image-preview" class="image-preview">
                          <label for="image-upload" id="image-label">Choose File</label>
                          <input type="file" name="image" id="image-upload" />
                        </div>
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Detail Bukti</label>
                      <div class="col-sm-12 col-md-7">
                        <textarea class="summernote-simple"></textarea>
                      </div>
                    </div>
                    <div class="card-footer text-right">
                      <button type="submit" class="btn btn-primary">Kirim</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  @endsection